# Generated by Django 4.2.6 on 2023-10-28 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_remove_doctor_timings_timing_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='time',
        ),
        migrations.AddField(
            model_name='appointment',
            name='timing',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='homepage.timing'),
            preserve_default=False,
        ),
    ]
